name: CDN & Multi-Cloud Deployment

on:
  workflow_dispatch:

jobs:
  cdn-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build assets
        run: npm run build
      - name: Upload to AWS S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-central-1'
          SOURCE_DIR: 'public/build'
      - name: Upload to Azure Blob
        uses: bacongobbler/azure-blob-storage-upload@v1.3.1
        with:
          source_dir: 'public/build'
          container_name: ${{ secrets.AZURE_CONTAINER }}
          connection_string: ${{ secrets.AZURE_CONNECTION_STRING }}
      - name: Purge Cloudflare Cache
        uses: jakejarvis/cloudflare-purge-action@master
        with:
          cf_zone: ${{ secrets.CLOUDFLARE_ZONE }}
          cf_auth_email: ${{ secrets.CLOUDFLARE_EMAIL }}
          cf_auth_key: ${{ secrets.CLOUDFLARE_KEY }}
      - name: Notify CDN Deploy
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: '{"text":"Assets deployed to AWS, Azure, and CDN; cache purged."}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
